Pass around the github client
The "malformed yaml" github action was broken because of the
error:

    /reject-malformed-yaml.rb:16:in `yaml_files_in_pr': undefined local variable or method `gh' for main:Object (NameError)
            from /reject-malformed-yaml.rb:12:in `malformed_yaml_files'
            from /reject-malformed-yaml.rb:28:in `<main>'

This commit should fix this.